# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85548f518cd84d58c040ae9632c64eac0782e4c9c9c05ba3fdbbc939691eab3495056284cd1ad68b2fb839e223c7f7bbc61aa321a2ba5aedb22445ff06f41041

test:
  secret_key_base: f08cf39b38498efdc6f92db2b18aeae0821122a9e0672911c6146c45e89bcbca0c1321ccbc20fd5933a4ba91a8d0d2f1727f3226f31e48c1214775d3c9875b7e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
